srcs/data/django/main/urls.py
# myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static
from .views import process_post_data
from .views import upload_image
from .views import heartbeat
from .views import ja

urlpatterns = [
    path('', views.index, name='index'),
    path('process-post/', process_post_data, name='process_post_data'),
    path('get-csrf-token/', views.get_csrf_token, name='get_csrf_token'),
    path('upload/', upload_image, name='upload_image'),    
    path('heartbeat/', heartbeat, name='heartbeat'),
    path('gameHeartbeat/<str:roomid>/', views.gameHeartbeat, name='gameHeartbeat'),
    path('getLanguage/<str:lang>/', views.getLanguage, name='getLanguage'),
    path('setLanguage/<str:lang>/', views.setLanguage, name='setLanguage'),
    path('i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

srcs/data/django/team_my2/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("", include("main.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
)

srcs/data/django/main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from .validators import validate_file_size
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.contrib.auth import get_user_model


class CustomUser(AbstractUser):
    avatar = models.CharField(
        max_length=255, 
        null=True, 
        blank=True,
        default='avatars/default.png'  # デフォルト画像のパスを指定
    )
    is_online = models.BooleanField(default=False) #オンラインステータス
    last_active = models.DateTimeField(default=timezone.now)  # 最後にアクティブだった時間
    display_name = models.CharField(max_length=255, unique=True, null=True, blank=True)
    email = models.EmailField(unique=True)
    language = models.CharField(default='ja')

    def send_friend_request(self, to_user):
        if self == to_user:
            raise ValidationError("You cannot send a friend request to yourself.")
        if FriendRequest.objects.filter(Q(from_user=self, to_user=to_user) | Q(from_user=to_user, to_user=self)).exists():
            raise ValidationError("You cannot send a friend request.")
        friend_request = FriendRequest(from_user=self, to_user=to_user)
        friend_request.save()
        return friend_request

    @property
    def wins(self):
        return Matchmaking.objects.filter(winner=self).count()

    @property
    def losses(self):
        return Matchmaking.objects.filter(
            Q(user1=self) | Q(user2=self),
            ~Q(winner=self),
            winner__isnull=False
        ).count()

    @property
    def win_rate(self):
        total_matches = self.wins + self.losses
        if total_matches > 0:
            return int((self.wins / total_matches) * 100)
        return 0

class Image(models.Model):
    image = models.ImageField(upload_to='avatars/', validators=[validate_file_size])

class FriendRequest(models.Model):
    from_user = models.ForeignKey(CustomUser, related_name='friend_requests_sent', on_delete=models.CASCADE)
    to_user = models.ForeignKey(CustomUser, related_name='friend_requests_received', on_delete=models.CASCADE)
    status = models.CharField(max_length=1, choices=[('P', 'Pending'), ('A', 'Accepted')], default='P')

    def accept_request(self):
        self.status = 'A'
        self.save()

class Tournament(models.Model):
    size = models.IntegerField(default=0)
    num_users = models.IntegerField(default=-1)
    timestamp = models.DateTimeField(auto_now=True)
    ball_speed = models.IntegerField(default=2)
    paddle_size = models.IntegerField(default=2)
    match_point = models.IntegerField(default=10)
    is_3d = models.BooleanField(default=False)

class TournamentUser(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_complete = models.BooleanField(default=False)

class Doubles(models.Model):
    num_users = models.IntegerField(default=-1)
    timestamp = models.DateTimeField(auto_now=True)
    ball_speed = models.IntegerField(default=2)
    paddle_size = models.IntegerField(default=2)
    match_point = models.IntegerField(default=10)
    is_3d = models.BooleanField(default=False)

class DoublesUser(models.Model):
    doubles = models.ForeignKey(Doubles, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_complete = models.BooleanField(default=False)

class Matchmaking(models.Model):
    user1 = models.ForeignKey(CustomUser, related_name='matchmaking_user1', on_delete=models.CASCADE, null=True, blank=True)
    user2 = models.ForeignKey(CustomUser, related_name='matchmaking_user2', on_delete=models.CASCADE, null=True, blank=True)
    user3 = models.ForeignKey(CustomUser, related_name='matchmaking_user3', on_delete=models.CASCADE, null=True, blank=True)
    user4 = models.ForeignKey(CustomUser, related_name='matchmaking_user4', on_delete=models.CASCADE, null=True, blank=True)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE, null=True, blank=True)  # トーナメントID
    doubles = models.ForeignKey(Doubles, on_delete=models.CASCADE, null=True, blank=True) #ダブルス
    timestamp = models.DateTimeField(auto_now=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    level = models.IntegerField(default=-1)
    ball_speed = models.IntegerField(default=2)
    paddle_size = models.IntegerField(default=2)
    match_point = models.IntegerField(default=10)
    is_3d = models.BooleanField(default=False)
    ai = models.IntegerField(default=2)
    is_single = models.BooleanField(default=False)
    point1 = models.IntegerField(default=0)
    point2 = models.IntegerField(default=0)
    winner = models.ForeignKey(CustomUser, related_name='winner', on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return f'Matchmaking ID {self.id} (Tournament: {self.tournament_id})'

srcs/data/django/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from .models import Image, FriendRequest, CustomUser, Matchmaking, Tournament, Doubles
import re
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.db.models import Q



class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = get_user_model() 
        fields = ('username', 'email', 'password1', 'password2')

class LoginForm(AuthenticationForm):
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                # ログ出力で何が起きているかを確認
                print("Authentication failed: Username or password is incorrect.")
                raise forms.ValidationError(
                    _("ユーザー名またはパスワードが正しくありません"),
                    code='invalid_login',
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

User = get_user_model()

class UsernameForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username']
    def __init__(self, *args, **kwargs):
        super(UsernameForm, self).__init__(*args, **kwargs)
        self.fields['username'].required = True
        del self.fields['password'] # パスワードフィールドを削除する

class EmailForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['email']
    def __init__(self, *args, **kwargs):
        super(EmailForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

class DisplayNameForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['display_name']
    def __init__(self, *args, **kwargs):
        super(DisplayNameForm, self).__init__(*args, **kwargs)
        self.fields['display_name'].required = True

class AvatarForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['avatar']
        widgets = {
            'avatar': forms.HiddenInput(),
        }
    def __init__(self, *args, **kwargs):
        super(AvatarForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].required = True

class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput(), label="Confirm password")

    class Meta:
        model = User
        fields = ['password']

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise ValidationError('パスワードは8文字以上である必要があります')
        if not re.findall('[a-zA-Z]', password):
            raise ValidationError('パスワードには少なくとも一つの文字が含まれている必要があります')
        return password

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and confirm_password and password != confirm_password:
            self.add_error('confirm_password', "同一のパスワードではありません")
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image']

class FriendRequestForm(forms.Form):
    to_user = forms.ModelChoiceField(queryset=CustomUser.objects.all(), label="Add Friend", required=False)

    def __init__(self, *args, **kwargs):
        self.from_user = kwargs.pop('from_user', None)
        super().__init__(*args, **kwargs)
        if self.from_user:
            # すでに友達申請を送ったユーザーとすでに友達になっているユーザーを取得
            pending_or_accepted_requests = FriendRequest.objects.filter(
                Q(from_user=self.from_user) | Q(to_user=self.from_user),
                Q(status='P') | Q(status='A')
            ).values_list('from_user', 'to_user')

            # 除外するユーザーのIDリストを作成
            excluded_user_ids = set()
            for from_user_id, to_user_id in pending_or_accepted_requests:
                if from_user_id != self.from_user.id:
                    excluded_user_ids.add(from_user_id)
                if to_user_id != self.from_user.id:
                    excluded_user_ids.add(to_user_id)

            # 自分自身、display_nameがNone、すでに友達申請を送ったまたはすでに友達になっているユーザーを除外
            self.fields['to_user'].queryset = CustomUser.objects.exclude(
                id__in=excluded_user_ids
            ).exclude(
                id=self.from_user.id
            ).exclude(
                display_name=None
            ).order_by('display_name')

        self.fields['to_user'].label_from_instance = self.label_from_instance

    def label_from_instance(self, obj):
        return obj.display_name


class FriendRequestActionForm(forms.Form):
    action = forms.ChoiceField(choices=[('accept', 'Accept')])

class CustomizeGameForm(forms.ModelForm):
    BALL_SPEED_CHOICES = [
        (2, '標準'),
        (1, '遅い'),
        (3, '速い'),
    ]
    ball_speed = forms.ChoiceField(choices=BALL_SPEED_CHOICES)

    PADDLE_SIZE_CHOICES = [
        (2, '標準'),
        (1, '小さい'),
        (3, '大きい'),
    ]
    paddle_size = forms.ChoiceField(choices=PADDLE_SIZE_CHOICES)

    MATCH_POINT_CHOICES = [
        (10, '10'),
        (15, '15'),
        (20, '20'),
    ]
    match_point = forms.ChoiceField(choices=MATCH_POINT_CHOICES)

    IS_3D_CHOICES = [
        (False, '2D'),
        (True, '3D'),
    ]
    is_3d = forms.ChoiceField(choices=IS_3D_CHOICES)

    class Meta:
        model = Matchmaking
        fields = ['ball_speed', 'paddle_size', 'match_point', 'is_3d']
    
class CustomizeSinglePlayForm(forms.ModelForm):
    BALL_SPEED_CHOICES = [
        (2, '標準'),
        (1, '遅い'),
        (3, '速い'),
    ]
    ball_speed = forms.ChoiceField(choices=BALL_SPEED_CHOICES)

    PADDLE_SIZE_CHOICES = [
        (2, '標準'),
        (1, '小さい'),
        (3, '大きい'),
    ]
    paddle_size = forms.ChoiceField(choices=PADDLE_SIZE_CHOICES)

    MATCH_POINT_CHOICES = [
        (10, '10'),
        (15, '15'),
        (20, '20'),
    ]
    match_point = forms.ChoiceField(choices=MATCH_POINT_CHOICES)

    IS_3D_CHOICES = [
        (False, '2D'),
        (True, '3D'),
    ]
    is_3d = forms.ChoiceField(choices=IS_3D_CHOICES)

    AI_CHOICES = [
        (2, "普通"),
        (1, "弱い"),
        (3, "強い"),
    ]
    ai = forms.ChoiceField(choices=AI_CHOICES)

    class Meta:
        model = Matchmaking
        fields = ['ball_speed', 'paddle_size', 'match_point', 'is_3d', 'ai']

class CustomizeTournamentForm(forms.ModelForm):
    BALL_SPEED_CHOICES = [
        (2, '標準'),
        (1, '遅い'),
        (3, '速い'),
    ]
    ball_speed = forms.ChoiceField(choices=BALL_SPEED_CHOICES)

    PADDLE_SIZE_CHOICES = [
        (2, '標準'),
        (1, '小さい'),
        (3, '大きい'),
    ]
    paddle_size = forms.ChoiceField(choices=PADDLE_SIZE_CHOICES)

    MATCH_POINT_CHOICES = [
        (10, '10'),
        (15, '15'),
        (20, '20'),
    ]
    match_point = forms.ChoiceField(choices=MATCH_POINT_CHOICES)

    IS_3D_CHOICES = [
        (False, '2D'),
        (True, '3D'),
    ]
    is_3d = forms.ChoiceField(choices=IS_3D_CHOICES)

    class Meta:
        model = Tournament
        fields = ['ball_speed', 'paddle_size', 'match_point', 'is_3d']

class CustomizeDoublesForm(forms.ModelForm):
    BALL_SPEED_CHOICES = [
        (2, '標準'),
        (1, '遅い'),
        (3, '速い'),
    ]
    ball_speed = forms.ChoiceField(choices=BALL_SPEED_CHOICES)

    PADDLE_SIZE_CHOICES = [
        (2, '標準'),
        (1, '小さい'),
        (3, '大きい'),
    ]
    paddle_size = forms.ChoiceField(choices=PADDLE_SIZE_CHOICES)

    MATCH_POINT_CHOICES = [
        (10, '10'),
        (15, '15'),
        (20, '20'),
    ]
    match_point = forms.ChoiceField(choices=MATCH_POINT_CHOICES)

    IS_3D_CHOICES = [
        (False, '2D'),
        (True, '3D'),
    ]
    is_3d = forms.ChoiceField(choices=IS_3D_CHOICES)

    class Meta:
        model = Doubles
        fields = ['ball_speed', 'paddle_size', 'match_point', 'is_3d']

srcs/data/django/main/templates/change_password.html
<form class="ajax-form px-5 mb-5" action="process-post/">
    <input type="hidden" name="page" value="change_password">
    {% csrf_token %}
    <div class="row g-3 align-items-center">
        <div class="mb-3 col-auto">
            <label for="id_password" class="form-label translations" id="change_password_header">　</label>
        </div>
        <div id="change_password_helper1" class="mb-4 col-auto translations">　</div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="mb-3 col-auto">
            <input type="password" class="form-control bg-dark text-light" name="password" id="id_password" value="{{ form_change_password.password.value|default_if_none:'' }}">
        </div>
        <div class="mb-3 col-auto">
            {% if form_change_password.password.errors %}
                {% for error in form_change_password.password.errors %}
                    {% if error == "パスワードは8文字以上である必要があります" %}
                        <div class="text-warning translations" id="change_password_warning1">　</div>
                    {% elif error == "パスワードには少なくとも一つの文字が含まれている必要があります" %}
                        <div class="text-warning translations" id="change_password_warning2">　</div>
                    {% endif %}
                {% endfor %}
            {% endif %}

        </div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="mb-3 col-auto">
            <label for="id_confirm_password" class="form-label translations" id="change_password_confirmation">　</label>
        </div>
        <div id="change_password_helper2" class="mb-4 col-auto translations">　</div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="mb-3 col-auto">
            <input type="password" class="form-control bg-dark text-light" name="confirm_password" id="id_confirm_password" value="{{ form_change_password.confirm_password.value|default_if_none:'' }}">
        </div>
        <div class="mb-3 col-auto">
            {% if form_change_password.confirm_password.errors %}
                {% for error in form_change_password.confirm_password.errors %}
                    {% if error == "同一のパスワードではありません" %}
                        <div class="text-warning translations" id="change_password_warning3">　</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <button type="submit" class="btn btn-primary translations" id="change_password_button">　</button>
</form>

srcs/data/django/main/templates/customize_game.html
<div class="px-5">
    <form class="ajax-form px-5" action="process-post/">
        <input type="hidden" name="page" value="create_room">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary mb-5 mt-3 translations" id="custom_game_button"  style="width: 20rem; height: 3rem;">　</button>
        <div class="accordion" >
            <div class="accordion-item" style="width: 20rem;">
                <h2 class="accordion-header">
                    <button class="accordion-button bg-primary text-light translations" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" id="custom_game_header" style="height: 2rem;">
                    　
                    </button>
                </h2>
            </div>
            <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionExample"  style="border: 1px solid #ddd; width: 20rem;">
                <div class="accordion-body">
                    <!-- Ball Speed Field -->
                    <div class="form-group row mb-3">
                        <label for="id_ball_speed" class="col-sm-1 col-form-label translations text-light" id="game_ball_speed" style="width: 10rem;">　</label>
                        <div class="col-sm-1" style="width: 8rem;">
                            <select name="ball_speed" id="id_ball_speed" class="form-select bg-dark text-light">
                                <option value="2" {% if form.ball_speed.value == "2" %}selected{% endif %} class="translations" id="game_ball_speed_normal">　</option>
                                <option value="1" {% if form.ball_speed.value == "1" %}selected{% endif %} class="translations" id="game_ball_speed_slow">　</option>
                                <option value="3" {% if form.ball_speed.value == "3" %}selected{% endif %} class="translations" id="game_ball_speed_fast">　</option>
                            </select>
                        </div>
                    </div>
                    <!-- Paddle Size Field -->
                    <div class="form-group row mb-3">
                        <label for="id_paddle_size" class="col-sm-1 col-form-label translations text-light" id="game_paddle_size" style="width: 10rem;">　</label>
                        <div class="col-sm-1" style="width: 8rem;">
                            <select name="paddle_size" id="id_paddle_size" class="form-select bg-dark text-light">
                                <option value="2" {% if form.paddle_size.value == "2" %}selected{% endif %} class="translations" id="game_paddle_size_normal">　</option>
                                <option value="1" {% if form.paddle_size.value == "1" %}selected{% endif %} class="translations" id="game_paddle_size_small">　</option>
                                <option value="3" {% if form.paddle_size.value == "3" %}selected{% endif %} class="translations" id="game_paddle_size_large">　</option>
                            </select>
                        </div>
                        </div>
                    <!-- Match Point Field -->
                    <div class="form-group row mb-3">
                        <label for="id_match_point" class="col-sm-1 col-form-label translations text-light" id="game_match_point" style="width: 10rem;">　</label>
                        <div class="col-sm-1" style="width: 8rem;">
                            <select name="match_point" id="id_match_point" class="form-select bg-dark text-light">
                                {% for value, label in form.match_point.field.choices %}
                                <option value="{{ value }}" {% if form.match_point.value == value %}selected{% endif %}>
                                    {{ label }}
                                </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <!-- Is 3D Field -->
                    <div class="form-group row mb-3">
                        <label for="id_is_3d" class="col-sm-1 col-form-label translations text-light" id="game_is_3d" style="width: 10rem;">　</label>
                        <div class="col-sm-1" style="width: 8rem;">
                            <select name="is_3d" id="id_is_3d" class="form-select bg-dark text-light">
                                {% for value, label in form.is_3d.field.choices %}
                                <option value="{{ value }}" {% if form.is_3d.value == value %}selected{% endif %}>
                                    {{ label }}
                                </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

srcs/data/django/main/templates/customize_single_play.html
<div class="px-5">
    <form class="ajax-form px-5" action="process-post/">
        <input type="hidden" name="page" value="single_play">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary mb-5 mt-3 translations" id="single_play_button" style="width: 20rem; height: 3rem;">　</button>
        <div class="accordion" >
            <div class="accordion-item" style="width: 20rem;">
                <h2 class="accordion-header">
                    <button class="accordion-button bg-primary text-light translations" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" id="single_play_header" style="height: 2rem;">
                    　
                    </button>
                </h2>
            </div>
            <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionExample" style="border: 1px solid #ddd; width: 20rem;">
                <div class="accordion-body">
                    <div class="form-group row mb-3">
                        <label for="id_ball_speed" class="col-sm-1 col-form-label translations text-light" id="single_ball_speed" style="width: 10rem;">　</label>
                        <div class="col-sm-1" style="width: 8rem;">
                            <select name="ball_speed" id="id_ball_speed" class="form-select bg-dark text-light">
                                <option value="2" {% if form.ball_speed.value == "2" %}selected{% endif %} class="translations" id="single_ball_speed_normal">　</option>
                                <option value="1" {% if form.ball_speed.value == "1" %}selected{% endif %} class="translations" id="single_ball_speed_slow">　</option>
                                <option value="3" {% if form.ball_speed.value == "3" %}selected{% endif %} class="translations" id="single_ball_speed_fast">　</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-3">
                        <label for="id_paddle_size" class="col-sm-1 col-form-label translations text-light" id="single_paddle_size" style="width: 10rem;">　</label>
                        <div class="col-sm-1" style="width: 8rem;">
                            <select name="paddle_size" id="id_paddle_size" class="form-select bg-dark text-light">
                                <option value="2" {% if form.paddle_size.value == "2" %}selected{% endif %} class="translations" id="single_paddle_size_normal">　</option>
                                <option value="1" {% if form.paddle_size.value == "1" %}selected{% endif %} class="translations" id="single_paddle_size_small">　</option>
                                <option value="3" {% if form.paddle_size.value == "3" %}selected{% endif %} class="translations" id="single_paddle_size_large">　</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-3">
                        <label for="id_match_point" class="col-sm-1 col-form-label translations text-light" id="single_match_point" style="width: 10rem;">　</label>
                        <div class="col-sm-1" style="width: 8rem;">
                            <select name="match_point" id="id_match_point" class="form-select bg-dark text-light">
                                {% for value, label in form.match_point.field.choices %}
                                <option value="{{ value }}" {% if form.match_point.value == value %}selected{% endif %}>
                                    {{ label }}
                                </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-3">
                        <label for="id_is_3d" class="col-sm-1 col-form-label translations text-light" id="single_is_3d" style="width: 10rem;">　</label>
                        <div class="col-sm-1" style="width: 8rem;">
                            <select name="is_3d" id="id_is_3d" class="form-select bg-dark text-light">
                                {% for value, label in form.is_3d.field.choices %}
                                <option value="{{ value }}" {% if form.is_3d.value == value %}selected{% endif %}>
                                    {{ label }}
                                </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mb-3">
                        <label for="id_ai" class="col-sm-1 col-form-label translations text-light" style="width: 10rem;">AI</label>
                        <div class="col-sm-1" style="width: 8rem;">
                            <select name="ai" id="id_ai" class="form-select bg-dark text-light">
                                <option value="2" {% if form.ai.value == "2" %}selected{% endif %} class="translations" id="single_ai_normal">　</option>
                                <option value="1" {% if form.ai.value == "1" %}selected{% endif %} class="translations" id="single_ai_weak">　</option>
                                <option value="3" {% if form.ai.value == "3" %}selected{% endif %} class="translations" id="single_ai_strong">　</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

srcs/data/django/main/templates/edit_avatar.html
<head>
    <style>
        .errorlist {
            display: none;
        }

        .custom-file-input {
            visibility: hidden;
            width: 1px;
            height: 1px;
        }
    </style>
</head>
<div class="px-5">
    <form id="uploadForm" class="ajax-upload" action="upload/" enctype="multipart/form-data">
        <div class="row g-3 align-items-center">
            <div class="mb-3 col-auto">
                <label for="id_email" class="form-label translations" id="edit_avatar_header">　</label>
            </div>
            <div id="edit_avatar_helper1" class="mb-4 col-auto translations">　</div>
        </div>
            <label for="image" class="btn btn-outline-info translations" id="edit_avatar_button1">　</label>
            <input type="file" id="image" name="image" class="custom-file-input">
            <button type="submit" class="btn btn-outline-info translations" id="edit_avatar_button2">　</button>
        </form>
        <!-- <form id="uploadForm" class="ajax-upload" action="upload/">
            <input type="file" id="image" name="image">
            <button type="submit" class="btn btn-secondary">アップロード</button>
        </form> -->
        <div id="descimage" class="form-text translations" id="edit_avatar_helper2">　</div>
        <img id="uploaded" src="media/{{request.user.avatar}}" alt="">
        <div id="result"></div>
        <form class="ajax-form" action="process-post/" enctype="multipart/form-data">
            <input type="hidden" name="page" value="edit_avatar">
            {% csrf_token %}
            {{ form_edit_avatar.as_p }}
            <div id="edit_avatar_helper3" class="mb-4 col-auto translations">　</div>
        <button type="submit" class="btn btn-primary translations" id="edit_avatar_button3">　</button>
    </form>
</div>
<hr></hr>

    

srcs/data/django/main/templates/edit_display_name.html
<form class="ajax-form px-5" action="process-post/">
    <input type="hidden" name="page" value="edit_display_name">
    {% csrf_token %}
    <div class="row g-3 align-items-center">
        <div class="mb-3 col-auto">
            <label for="id_display_name" class="form-label translations" id="edit_display_name_header">　</label>
        </div>
        <div id="edit_display_name_helper" class="mb-4 col-auto translations">　</div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="mb-3 col-auto">
            <input type="text" class="form-control bg-dark text-light" name="display_name" id="id_display_name" value="{{ form_edit_display_name.display_name.value|default_if_none:'' }}">
        </div>
        {% if form_edit_display_name.display_name.errors %}
            {% for error in form_edit_display_name.display_name.errors %}
                {% if error != "このフィールドは必須です。" %}
                    <div class="text-warning translations mb-3 col-auto" id="edit_display_name_warning">　</div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary translations" id="edit_display_name_button">　</button>
</form>
<hr></hr>

srcs/data/django/main/templates/index.html
{% extends 'global_base.html' %}
{% load static %}

{% block title %}Top Page{% endblock %}
{% block headerscript %}
{% endblock %}
{% block headerscriptfile %}
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}

{% endblock %}

{% block foot %}
{% endblock %}